### ISSUE TITLE
PlatformIO 쓰기

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/arduino-practice#1]
#### [PlatformIO](http://platformio.org/)

IoT 하는 사람들 사이에서의 de facto standard 같음

**Comment by raysuhyunlee** [comment]
오오 좋은 IDE다

**Comment by simnalamburt** [comment]
이거 쓰면 커맨드라인에서 모든거 다 할 수 있고, CI도 걸 수 있을듯

**Comment by simnalamburt** [comment]
Closed by ce4e30ecfad49badcc32fcc89220eecb65f4270c
